name        'willdurand-nodejs'
version     '0.0.3'
summary     'This module allows to install Node.js and NPM.'
description 'This module allows to install Node.js and NPM.'
license     'MIT'
author      'William Durand'
